### PR TITLE
Allow disabling of the title menu item

### PR DESCRIPTION
**Pull request by joblo2213**
Hey there! First of all thanks for your work on this lib, it's really serving me well!

Only bummer is that I can't disable or customize the title item in the tray menu.  
This leads to a very specific issue with my application as the main stage is not meant to be shown that way. 

So it would be great if I could just disable the title as it has no use in my application anyway,

### CODE REVIEW

**Comment by dustinkredmond** [comment]
@joblo2213 Since I've deprecated `fxTrayIcon.showMinimal()` in favor of providing no default MenuItems in a future release, (we'll only have the `fxTrayIcon.show()` method), I will merge this request.

Since it changes public API in a potentially breaking way, you can expect to see this released under version 3.x.x. Time permitting, I will release this to Maven Central after work today, if not, by the end of the week for sure.

I'm glad that you like the library. If you wish, you can create a PR to add a link to your project that uses FXTrayIcon to our README file. We like to highlight projects that use the library. Thank you for contributing! 👍🏻

**Comment by joblo2213** [comment]
Thanks a lot for the quick merge, I'm looking forward to the release.

With adding JMacros to your README I'dd prefer to wait till it is at a more stable state. Currently it's still pretty bleeding edge so I don't feel comfortable with exposing it to a bigger audience. 😅 

But You'll here from me once I get closer to a stable release.

**Comment by dustinkredmond** [comment]
@joblo2213 Understood regarding adding JMacros. I look forward to seeing it once it's stable. It looks like an application that I would be **very** interested in using. 😄

**Comment by dustinkredmond** [comment]
@joblo2213 Release 3.0.0 has just been pushed to Maven. It contains your merged PR.

I did, however, make the default behavior **not** to show both the title bar menu item and the exit menu item.
Developers can get those by called the appropriate `add` methods and passing true.

**Comment by joblo2213** [comment]
I actually prefer this. Only did it the other way around as I didn't want the changes to be API breaking.

**Comment by dustinkredmond** [comment]
@joblo2213 I had a few other API breaking things I wanted to get out of the way as well, so I decided a major version release wouldn't hurt. I agree, this way feels more natural.

**Pull request merged**
