### PR TITLE
Support CheckMenuItem as menu item

### PR DESCRIPTION
**Pull request by azplanlos**
This PR introduces support for CheckMenuItem as menu item as discussed in #51 - Might need JDK 9 to compile but not sure about this.

### CODE REVIEW

**Comment by dustinkredmond** [comment]
This is perfect, I will merge. Thank you for your contribution!

**Comment by EasyG0ing1** [comment]
@azplanlos - I created this class, but the onAction event doesn't work ... any thoughts?

```java

import javafx.application.Application;
import javafx.scene.control.CheckMenuItem;
import javafx.stage.Stage;

public class CheckMenu  extends Application {

	CheckMenuItem cmuApples = new CheckMenuItem("Apples");
	CheckMenuItem cmuOranges = new CheckMenuItem("Oranges");
	CheckMenuItem cmuPears = new CheckMenuItem("Pears");

	@Override
	public void start(Stage primaryStage) {
		primaryStage.setTitle("Default Icon");

		FXTrayIcon fxti = new FXTrayIcon.Builder(primaryStage)
				.show()
				.build();

		cmuApples.setOnAction(e->{
			if(cmuApples.isSelected()) {
				cmuOranges.setSelected(false);
				cmuPears.setSelected(false);
			}
		});

		cmuOranges.setOnAction(e->{
			if(cmuApples.isSelected()) {
				cmuApples.setSelected(false);
				cmuPears.setSelected(false);
			}
		});

		cmuPears.setOnAction(e->{
			if(cmuApples.isSelected()) {
				cmuApples.setSelected(false);
				cmuOranges.setSelected(false);
			}
		});

		fxti.addMenuItem(cmuApples);
		fxti.addMenuItem(cmuOranges);
		fxti.addMenuItem(cmuPears);

	}

	public static void main(String[] args) {
		launch(args);
	}
}
```

**Comment by azplanlos** [comment]
Hi Michael,

You are right, this might be a limitation of my implementation. As the JavaFX MenuItems aren‘t bound to their Swing version you can’t set the checked property afterwards. If you need this, let me have a look if it can be done.

Andreas
________________________________
Von: Michael Sims ***@***.***>
Gesendet: Tuesday, June 14, 2022 11:11:12 PM
An: dustinkredmond/FXTrayIcon ***@***.***>
Cc: Andreas Zöllner ***@***.***>; Mention ***@***.***>
Betreff: Re: [dustinkredmond/FXTrayIcon] Support CheckMenuItem as menu item (PR #55)


@azplanlos<https://github.com/azplanlos> - I created this class, but the onAction event doesn't work ... any thoughts?

import javafx.application.Application;
import javafx.scene.control.CheckMenuItem;
import javafx.stage.Stage;

public class CheckMenu  extends Application {

        CheckMenuItem cmuApples = new CheckMenuItem("Apples");
        CheckMenuItem cmuOranges = new CheckMenuItem("Oranges");
        CheckMenuItem cmuPears = new CheckMenuItem("Pears");

        @Override
        public void start(Stage primaryStage) {
                primaryStage.setTitle("Default Icon");

                FXTrayIcon fxti = new FXTrayIcon.Builder(primaryStage)
                                .show()
                                .build();

                cmuApples.setOnAction(e->{
                        if(cmuApples.isSelected()) {
                                cmuOranges.setSelected(false);
                                cmuPears.setSelected(false);
                        }
                });

                cmuOranges.setOnAction(e->{
                        if(cmuApples.isSelected()) {
                                cmuApples.setSelected(false);
                                cmuPears.setSelected(false);
                        }
                });

                cmuPears.setOnAction(e->{
                        if(cmuApples.isSelected()) {
                                cmuApples.setSelected(false);
                                cmuOranges.setSelected(false);
                        }
                });

                fxti.addMenuItem(cmuApples);
                fxti.addMenuItem(cmuOranges);
                fxti.addMenuItem(cmuPears);

        }

        public static void main(String[] args) {
                launch(args);
        }
}

**Comment by EasyG0ing1** [comment]
@azplanlos - Already got it ... [PR #56](https://github.com/dustinkredmond/FXTrayIcon/pull/56)

**Pull request merged**
