### PR TITLE
Builder class correction and some other changes...

### PR DESCRIPTION
**Pull request by EasyG0ing1**
Re-structured the Builder class so that it now conforms to "proper" Builder style. The Builder class now only accepts options that are desired, then the build() method returns a new instance of FXTrayIcon via a private constructor that only accepts an instance of the Builder class as the argument. That constructor then first calls FXTrayIcons main constructor then it proceeds to configure all of the options that were set in the Builder class, including optional MenuItems and other desired behaviors.

Configured default icon size to be set based on operating system both in Builder and parent constructors - if there is no value passed into the library for icon dimensions.

Added an overloaded constructor where only the parentStage is required. FXTrayIcon will use a default graphic for the trayIcon when this constructor is used. This feature existed already in the Builder class, I simply extended it to the parent constructors.

Also tested every runnable test, updated some to use the builder class and replaced the old purple chain icon with the modern looking icon.

### CODE REVIEW

**Comment by dustinkredmond** [comment]
@EasyG0ing1, is this PR ready for merge? I see that the build is failing due to an error in a test class (TestFXTrayIcon). Travis CI shouldn't be running this test when in a headless environment, so this is no huge issue. I can resolve that with another commit. I'm ready to merge #27 if you're done with it. Thanks!

**Comment by EasyG0ing1** [comment]
@dustinkredmond I added this to the POM file which excludes tests in the Maven build process, but I'm not sure if that will affect the project when you try to publish it.
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.22.0</version>
    <configuration>
        <excludes>
            <exclude>**/*.java</exclude>
        </excludes>
    </configuration>
</plugin>
```

**Comment by dustinkredmond** [comment]
Good enough for me! I need to include some additional logic to check if the tests are being run in a headless environment, but that shouldn't delay these changes. I'm merging and will try to get a release pushed today.

Thank you for your hard work on this!

**Comment by EasyG0ing1** [comment]
@dustinkredmond I've affectionately named your build checker the Java Bridge Troll ... think Montey Python ... ;-)

And you're most welcome, these are fun projects for me.

**Pull request merged**
