### PR TITLE
Added a test app

### PR DESCRIPTION
**Pull request by EasyG0ing1**
Added a test app that demonstrates how to remove the applications TaskBar icon from windows or the Dock icon from a mac, leaving you with a pure SystemTray icon app only.

Also removed the word 'with' before subtitle from the osascript execute string in method showMacAlert.

### CODE REVIEW

**Comment by dustinkredmond** [comment]
@EasyG0ing1 Sorry for being picky. 😅 Could you please consolidate the new test application into one class (include the main() method in the same class as the overriden JavaFX start() method)?

Codacy is complaining about the underscore character in the class name, per java convention underscores aren't recommended.

There's also some dangling javadoc `/**` used to start a multiline comment instead of `/*`, and I noticed a `System.out.println("Is Mac");` statement that you probably added during testing.

If you could please fix this, I will merge. Thanks for noticing my error in generating the AppleScript string. I would have *never* caught this on my own.

**Comment by EasyG0ing1** [comment]
Man I guess I really should clean up after I'm done partying ... lol

I forgot to mention that I did originally attempt to do this with one class, but the starting class cannot be a class that extends Application. So I tried adding the Application class as a subclass the starting class, but then Java doesn't like it.

For example, this:

```
package com.dustinredmond.fxtrayicon;

import javafx.application.Application;
import javafx.scene.control.MenuItem;
import javafx.stage.Stage;

public class NoTaskBarIcon {
	public static void main(String[] args) {

		// This is an awt property which removes the icon
		// from the Dock on a mac and the TaskBar on Windows
		System.setProperty("apple.awt.UIElement", "true");
		java.awt.Toolkit.getDefaultToolkit();

		// This is a call to JavaFX application main method.
		// From now on we are transferring control to FX application.
		NoTaskBarIconMain.main(args);
	}
}

 class NoTaskBarIconMain extends Application {

	private static final String TEST_ICON = "icons8-link-64.png";
	private static FXTrayIcon icon;

	@Override
	public void start(Stage primaryStage) throws Exception {
		if (FXTrayIcon.isSupported()){
			icon = new FXTrayIcon(primaryStage, getClass().getResource(TEST_ICON));
			MenuItem menuShowStage   = new MenuItem("Show Scene");
			MenuItem menuShowMessage = new MenuItem("Show Message");
			MenuItem menuExit        = new MenuItem("Exit");
			menuShowStage.setOnAction(e->primaryStage.show());
			menuShowMessage.setOnAction(e->showMessage());
			menuExit.setOnAction(e-> System.exit(0));
			icon.addMenuItem(menuShowStage);
			icon.addMenuItem(menuShowMessage);
			icon.addMenuItem(menuExit);
			icon.showMinimal();
		}
	}

	private void showMessage() {
		icon.showInfoMessage("Check It Out!","Look Ma, No Taskbar Icon!");
	}


	public static void main(String[] args) {
		launch(args);
	}
}

```

Gives this:

> Exception in Application constructor
> Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class com.dustinredmond.fxtrayicon.NoTaskBarIconMain
> 	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:907)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NoSuchMethodException: com.dustinredmond.fxtrayicon.NoTaskBarIconMain.<init>()
> 	at java.lang.Class.getConstructor0(Class.java:3082)
> 	at java.lang.Class.getConstructor(Class.java:1825)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$7(LauncherImpl.java:818)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
> 	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
> 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

and if I change

` NoTaskBarIconMain.main(args);`

to 

`NoTaskBarIconMain.launch(args);
`
I get this:

> Exception in thread "main" java.lang.RuntimeException: Error: class com.dustinredmond.fxtrayicon.NoTaskBarIcon is not a subclass of javafx.application.Application
> 	at javafx.application.Application.launch(Application.java:254)
> 	at com.dustinredmond.fxtrayicon.NoTaskBarIcon.main(NoTaskBarIcon.java:17)
>

**Comment by EasyG0ing1** [comment]
@dustinkredmond 

Actually I think I found a way to do this with pure FX without needing AWT to launch ...

**Comment by EasyG0ing1** [comment]
@dustinkredmond 

OK, so the only way to do this ... getting rid of the TaskBar icon with JavaFX is by editing a file that only exists on a mac anyways, in the application package after it has been compiled and placed in the Applications folder. So it cant be done from the IDE unless it is done using AWT. And to do it THAT way, AWT has to set a system property BEFORE FX launches, so the ap has to launch from a class that doesn't extend application, then when its done, it can call a class that starts FX. 

And like I said, I couldn't make it work from a class / subclass method, I had to have to separate class files for some reason. I haven't looked into it further but i will do that now and see if it's even possible to do it from one class. My gut tells me no, because of the whole extending application thing ... I just have the feeling that when you extend an object into a class, that it will want dominance over the whole class including sub-classes so that calling it only from a subclass is kind of like ... trying to fit it in through the back door when clearly it needs to be up-front and foremost... and if sneaks in through the back, then its just gonna rain on you parade and try to take over anyways.

**Review by dustinkredmond — APPROVED** [review]
@EasyG0ing1 I'll go ahead and merge, I've still yet to give it a good test, but I know you always do. Thanks for this!

**Pull request merged**
